[mypy]
python_version = 3.9
files = src/budgettrace
check_untyped_defs = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = False
ignore_missing_imports = True
disable_error_code =
    arg-type,
    assignment,
    attr-defined,
    call-overload,
    dict-item,
    index,
    misc,
    str-format,
    union-attr,
    var-annotated
